### ISSUE TITLE
BUG: mdadm does not work properly

### ISSUE THREAD

**Issue by tzabbi** [siderolabs/extensions#489] opened 2024-10-13 08:03 UTC
Hey there, I'm using a bare metal single node cluster with 4 18 TB HDD drives. I start a pod in privileged mode and with a host filesystem mount. 

Pod yaml definition:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fedora
  namespace: default
spec:
  containers:
  - image: fedora
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep 1d"]
    name: debugger
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN"]
    volumeMounts:
    - mountPath: /host
      name: host-root
  hostIPC: true
  hostNetwork: true
  hostPID: true
  nodeName: master
  volumes:
  - hostPath:
      path: /
    name: host-root
```

And run the following commands in the pod:

```shell
chroot /host/ mdadm --create --verbose /dev/md0 --metadata=1.2 --level=10 --raid-devices=4  /dev/sda /dev/sdb /dev/sdc /dev/sdd
chroot /host mdadm --detail --scan 
```

Everything runs without any issues and the appropriate device file (/host/dev/md0) is created. But when I apply the new configuration to talos with the mount it needs a restart and the device file is gone and talos is unable to find the device file.

**Comment by smira** [comment] 2024-10-15 08:15
You haven't specified the version of Talos.

**Comment by tzabbi** [comment] 2024-10-15 08:19
Sorry, you are right. I'm using latest Talos (1.8.1) with the mdadm extension version v4.3.

**Comment by smira** [comment] 2024-10-15 11:17
We probably need the support bundle (`talosctl support`) after the reboot when the things fail, as this sounds like an issue with the udevd not activating the mdadm.

**Comment by tzabbi** [comment] 2024-10-15 16:22
System information:
* image from imagefactory: factory.talos.dev/installer-secureboot/82b20f562233148f8ae56d6c8080c95b1806fbb35d2e6d7e9eadd5490054c836:v1.8.1
* enabled extensions: 
   * siderolabs/i915-ucode
   * siderolabs/intel-ucode
   * siderolabs/mdadm
* zero kernel paramters

Comands I run:

```bash
❯ talosctl get extensions
NODE            NAMESPACE   TYPE              ID   VERSION   NAME          VERSION
192.168.1.210   runtime     ExtensionStatus   0    1         i915-ucode    20240909
192.168.1.210   runtime     ExtensionStatus   1    1         intel-ucode   20240910
192.168.1.210   runtime     ExtensionStatus   2    1         mdadm         v4.3
192.168.1.210   runtime     ExtensionStatus   3    1         schematic     82b20f562233148f8ae56d6c8080c95b1806fbb35d2e6d7e9eadd5490054c836

# In container i run the following commands:
[root@talos-controlplane /]# chroot /host mdadm --create --verbose /dev/md0 --metadata=1.2 --level=10 --raid-devices=4 /dev/sda /dev/sdb /dev/sdc /dev/sdd
[root@talos-controlplane /]# ls /host/dev/md0
/host/dev/md0



❯ talosctl get discoveredvolumes | grep md0
192.168.1.210   runtime     DiscoveredVolume   md0         1         disk        36 TB                                    
❯ talosctl reboot
watching nodes: [192.168.1.210]
    * 192.168.1.210: post check passed
❯ talosctl get discoveredvolumes | grep md0
❯
```
Support file:
[support.zip](https://github.com/user-attachments/files/17381677/support.zip)

**Comment by frezbo** [comment] 2024-10-16 07:16
This is due to md0 being renamed to usually md127 on reboots, better to use `/dev/md/<array-name>` so it's consistent

**Comment by tzabbi** [comment] 2024-10-16 07:32
Can you explain a little bit more?
I don't see anything with md?
![image](https://github.com/user-attachments/assets/7b6f0cbf-b144-4916-8cc0-a2522001646e)

And with the debug pod directly on the talos node:
![image](https://github.com/user-attachments/assets/0fb10119-c01c-401f-9c5e-8b8b39694e97)

**Comment by frezbo** [comment] 2024-10-16 07:35
> Can you explain a little bit more? I don't see anything with md? ![image](https://private-user-images.githubusercontent.com/40226087/376939003-7b6f0cbf-b144-4916-8cc0-a2522001646e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjQzMTEsIm5iZiI6MTcyOTA2NDAxMSwicGF0aCI6Ii80MDIyNjA4Ny8zNzY5MzkwMDMtN2I2ZjBjYmYtYjE0NC00OTE2LThjYzAtYTI1MjIwMDE2NDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODhhMWFjYmQyYzE4NGQzZWRlODMxNjJhYjc0YzMzYWVlODJjMGExN2M0MjVkNTg2MDc5ZmVhYmE5MjNkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MHhl8ZrcSngZ-Ft9LeVDa6vJvFVjl6JSxpWD2z8uAlk)
> 
> And with the debug pod directly on the talos node: ![image](https://private-user-images.githubusercontent.com/40226087/376939345-0fb10119-c01c-401f-9c5e-8b8b39694e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjQzMTEsIm5iZiI6MTcyOTA2NDAxMSwicGF0aCI6Ii80MDIyNjA4Ny8zNzY5MzkzNDUtMGZiMTAxMTktYzAxYy00MDFmLTljNWUtOGI4YjM5Njk0ZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzMwZGQ2MzJmMmU2ZWJkMzQ5NmI3YWEzY2FhNDI5ZDRmYTNlZjU0NDlmYTk2OTU1YzBhYzI5ZTZhZDk4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TGh88KSXE_VHbGxXKKiOeng6u8csOOdIgiWOMZcCz04)

It could be the fact that you create the `md` device using chroot, could you try this from a privileged pod with `hostPID` set to true.


```bash
nsenter --mount=/proc/1/ns/mnt -- chroot /host/ mdadm --create --verbose /dev/md0 --metadata=1.2 --level=10 --raid-devices=4  /dev/sda /dev/sdb /dev/sdc /dev/sdd
```

instead of chroot, i believe the mount is only visible in the pod mount namespace

**Comment by tzabbi** [comment] 2024-10-16 08:27
got this error: 

![image](https://github.com/user-attachments/assets/bef03c7d-8063-46bb-ae8f-1b0373311382)

**Comment by frezbo** [comment] 2024-10-16 08:42
sorry, just copy paste error:

```bash
nsenter --mount=/proc/1/ns/mnt -- mdadm --create --verbose /dev/md0 --metadata=1.2 --level=10 --raid-devices=4  /dev/sda /dev/sdb /dev/sdc /dev/sdd
```

**Comment by tzabbi** [comment] 2024-10-16 08:47
No worries, this time it worked:
![image](https://github.com/user-attachments/assets/1343e682-bcc1-49b1-a613-1f0f63c3983b)

But after a reboot the raid is gone again
![image](https://github.com/user-attachments/assets/86b66366-bc9a-4f38-a109-a497d0c6ba9b)
![image](https://github.com/user-attachments/assets/d6aec42d-6b6a-4903-ab8d-c9bbdc57116d)

**Comment by frezbo** [comment] 2024-10-16 08:48
what does a `talosctl ls /dev` show?

**Comment by tzabbi** [comment] 2024-10-16 08:49
The same:

![image](https://github.com/user-attachments/assets/7f64a998-d938-4e6c-ac69-a2a78fa9d45b)

**Comment by frezbo** [comment] 2024-10-16 08:51
okay, thanks, I'll try to re-create with level 10 and four block devices

**Comment by tzabbi** [comment] 2024-10-16 08:52
If you need something from me don't hesitate to contact me. I really appriciate your help and time!

**Comment by frezbo** [comment] 2024-10-16 09:28
hm I'm not able to reproduce, could you provide the machine config snipped used with the md device reference?

**Comment by tzabbi** [comment] 2024-10-16 09:34
what do you mean? I just have an custom Talos image which has the three extensions in it and secureboot on. The other part of the config is the creation of the mountpoint, which is currently commented out because Talos does not find the device file.

**Comment by frezbo** [comment] 2024-10-16 09:37
> what do you mean? I just have an custom Talos image which has the three extensions in it and secureboot on. The other part of the config is the creation of the mountpoint, which is currently commented out because Talos does not find the device file.

just need the commented mountpoint config used in machine config

**Comment by tzabbi** [comment] 2024-10-16 09:43
```yaml
machine:
  disks:
        - device: /dev/disk/by-id/md-uuid-<uuid>
          partitions:
            - mountpoint: /var/mnt/sata
```

**Comment by frezbo** [comment] 2024-10-16 13:53
> what do you mean? I just have an custom Talos image which has the three extensions in it and secureboot on. The other part of the config is the creation of the mountpoint, which is currently commented out because Talos does not find the device file.

what other extensions are used? I wonder if the other extensions are causing an issue, since I always see the md device after reboot

**Comment by tzabbi** [comment] 2024-10-16 14:01
These three:
siderolabs/i915-ucode
siderolabs/intel-ucode
siderolabs/mdadm

**Comment by frezbo** [comment] 2024-10-16 16:17
I also tested with a secureboot setup and I cannot reproduce this at all, after reboot the md array is always present, from your support zip it seems it was trying to load zfs extension (just a red-herring)

**Comment by tzabbi** [comment] 2024-10-16 16:48
I tried out zfs. But because of your requests I changed back. So it can be that some zfs loggs are there.

**Comment by tzabbi** [comment] 2024-10-16 17:20
If you want we can make an appointment with a call and I can share my screen^^

**Comment by frezbo** [comment] 2024-10-18 11:47
https://unix.stackexchange.com/questions/766784/single-drive-added-to-mdadm-raid-disappears-after-reboot

This was due to the disks already having some gpt partition table on the disks, wiping with `wipefs -a` on the disks and re-creating the md array fixed the issue

**Comment by tzabbi** [comment] 2024-10-18 13:34
@frezbo Thanks a lot! It was a really nice debug session with you! I will provide an updated README.md

**Comment by smira** [comment] 2024-10-18 15:06
@frezbo should we close it now?

**Comment by frezbo** [comment] 2024-10-18 15:34
> @frezbo should we close it now?

Yeh we can

**Closed by frezbo** 2024-10-18 15:34 UTC
