### ISSUE TITLE
nvidia-device-plugin won't start on talos 1.3.0

### ISSUE THREAD

**Issue by mdallaire** [siderolabs/extensions#101] opened 2022-12-16 02:36 UTC
After upgrading my nvidia node to talos 1.3.0 and recompiling and applying the nvidia proprietary driver my nvidia-device-plugin deployment no longer start with the following error:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to generate new device filter program from existing programs: unable to create new device filters program: load program: invalid argument: last insn is not an exit or jmp
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0: unknown
```

My research on this error seem to point to cgroups v2 compatibility and indeed reverting one of the node to cgroups v1 allowed the container to start.

libnvidia-container appears to support cgroups v2 since [v1.8.0](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0)

and v1.8.1 brings a fix to cgroup detection https://github.com/NVIDIA/libnvidia-container/issues/158

I have to admit this is getting a bit beyond my scope of knowledge but seeing as there is reference to permissions and capacities I figured it may be related since talos locks down a lot of things.

**Comment by smira** [comment] 2022-12-16 10:20
Did it work with Talos 1.2.x?

Talos 1.3.x defaults to cgroups v2 like previous versions of Talos, but adds optional support for cgroups v1.

**Comment by mdallaire** [comment] 2022-12-16 13:41
Sorry I could have made this clearer.

1. My systems were talos 1.2.7 installed with the proprietary nvidia install image build from https://www.talos.dev/v1.2/talos-guides/configuration/nvidia-gpu-proprietary/ and working perfectly with the nvidia-device-plugin helm chart
2. I upgraded to 1.3.0 with rebuilt proprietary drivers and the nvidia-device-plugin containers would no longer start
3. After some digging I switched the cgroups to v1 on those GPU nodes and the nvidia-device-plugin started working again.

> Talos 1.3.x defaults to cgroups v2 like previous versions of Talos, but adds optional support for cgroups v1.

Then I misunderstood the release notes. I did not get that it was already defaulting to v2 previously.

I am not sure then why it would fail on 1.3.0 with cgoups v2.

**Comment by frezbo** [comment] 2022-12-16 14:42
Talos always used cgroupv2, 1.3 just added support to forcefully use cgroupsv1 for very legacy workloads. One thing that changed between v1.2 and v1.3 of the extensions is the nvidia-container-runtime version, it was 1.10 with v1.2 i believe, i wonder if that's the issue :thinking:

**Comment by mdallaire** [comment] 2022-12-16 14:52
Would it be helpful to revert the extension to 1.10 and remove cgroups v1 just to test? I have a node I can play around with if you would like help troubleshooting deeper.

**Comment by frezbo** [comment] 2022-12-16 14:55
> Would it be helpful to revert the extension to 1.10 and remove cgroups v1 

cgroups v1 is something you'd have to force via a kernel arg on Talos to use, so that's just not relevant here. I'll first spin up a NVIDIA node to test with 1.3.0 and then if it doesn't work will provide a custom build with 1.10 nvidia-runtime to check

**Comment by mdallaire** [comment] 2022-12-16 14:58
> cgroups v1 is something you'd have to force via a kernel arg on Talos to use, so that's just not relevant here. I'll first spin up a NVIDIA node to test with 1.3.0 and then if it doesn't work will provide a custom build with 1.10 nvidia-runtime to check

It is relevant since adding the following to my GPU nodes is what made the nvidia plugin work in the end:
```
   install:
    disk: /dev/nvme0n1
    extraKernelArgs:
      - talos.unified_cgroup_hierarchy=0
  ```

**Comment by frezbo** [comment] 2022-12-16 15:01
oh i meant talos only supported cgroupsv2 and the nvidia plugin worked with Talos v1.2, so forcing to use cgroupsv1 is kind of a hack

**Comment by mdallaire** [comment] 2022-12-16 15:04
Ok! Let me know if you need anything from me. I am also on the Siderolab Slack if you want to reach out.

**Comment by frezbo** [comment] 2022-12-19 15:03
I can't reproduce the issue, tested with both the oss and proprietary drivers and it just works fine. I wonder if your build got corrupted.

**Comment by smira** [comment] 2022-12-26 12:58
Closing this one, please re-open if the issue persists

**Closed by smira** 2022-12-26 12:58 UTC
